environment:
  package_semantic_version: 4.0.0
  assembly_semantic_version: 4.0.0

version: $(package_semantic_version).{build}

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(assembly_semantic_version).0'
  assembly_file_version: '$(appveyor_build_version)'
  assembly_informational_version: '$(package_semantic_version)-CI-{build}'

before_build:
  - dotnet --info
  - dotnet restore

test_script:
  - dotnet test test/Autofac.Extras.Moq.Test

after_test:
  - dotnet pack -c Release src/Autofac.Extras.Moq
    
artifacts:
  - path: 'src\Autofac.Extras.Moq\bin\Release\*.nupkg'

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/autofac/api/v2/package
    api_key:
      secure: rCUEY75fXN0wxtMy6QL4jCrLdaYbxIBzIXWeN+wEu/XDpyqimzreOc5AH5jMd5ah
    skip_symbols: false
    symbol_server: https://nuget.symbolsource.org/MyGet/autofac
